name: Frontend CI

on:
  pull_request:
    branches: [ main, develop, CiTest ]
    paths: 
      - 'src/**'

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: yarn install
      
    - name: Run Linter
      run: yarn lint # Asegúrate de tener un script "lint" en tu package.json

    - name: Build Project
      run: yarn build # Asegúrate de tener un script "build" en tu package.json

    - name: Run Lighthouse Audit
      uses: treosh/lighthouse-ci-action@v8
      with:
        urls: |
          http://localhost:5173/
        config: |
          {
            "ci": {
              "collect": {
                "url": [
                  "http://localhost/"
                ],
                "startServerCommand": "yarn start"
              },
              "assert": {
                "assertions": {
                  "categories:performance": ["error", { "minScore": 0.9 }],
                  "categories:best-practices": ["error", { "minScore": 0.9 }]
                }
              }
            }
          }
        temporaryPublicStorage: true # Esto publicará el reporte de Lighthouse, útil para PRs
